version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432

  pga:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: lukasmolin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports: 
      - 3334:80
      - 3335:443
